FROM python:slim

WORKDIR /app

COPY . .
RUN apt-get update && apt-get install -y build-essential
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 5000

CMD flask db init; \
    flask db stamp head ; \
    flask db migrate; \
    flask db upgrade; \
    flask run --host=0.0.0.0
