FROM python:slim

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
    
COPY . .

CMD flask db init; flask db migrate; flask db upgrade; flask run --host=0.0.0.0