services:
  db:
    image: postgres
    restart: always
    container_name: db
    networks:
      - backend-network
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ## GEP

  gep_backend:
    build:
      context: ./lasic-gep-back
      dockerfile: Dockerfile
        #restart: always
    container_name: gep_backend
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/db-gep-back
      FRONTEND_URL: "http://gep.lasicifce.com"
      BACKEND_URL: "http://gep_backend:5000"

  ## CDC
  cdc_backend:
    build:
      context: ./centralcompras-back
      dockerfile: Dockerfile
        #    restart: always
    container_name: cdc_backend
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: cdc_db
      FRONTEND_URL: http://cdc.lasicifce.com/
      BACKEND_URL: http://cdc_backend:5000/

  ## CES
  redis:
    image: redis:latest
      #restart: always
    container_name: redis
    networks:
      - backend-network
    expose:
      - "6380"
    depends_on:
      - db
    volumes:
      - cache:/data

  ces_backend:
    build:
      context: ./lasic-ches-back
      dockerfile: Dockerfile
        #restart: always
    container_name: ces_back
    expose:
      - "8006"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ces_db
      FLASK_DEBUG: "true"
      FLASK_RUN_PORT: 8006
      BACKEND_URL: http://ces_backend:8006
      FRONTEND_URL: http://ces.lasicifce.com:81
      REDIS_OM_URL: redis://default:admin@redis:6380/0
  nginx:
    image: nginx:latest
    container_name: nginx-proxy2
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network
    depends_on:
      - gep_backend
      - ces_backend
      - cdc_backend


volumes:
  cache:

networks:
  backend-network:
    driver: bridge
