services: 
  gep_frontend:
    build:
      context: ./lasic-gep-front-next
      dockerfile: Dockerfile
    restart: always
    container_name: gep_frontend
    volumes:
      - gep_static:/home/node/app/.next
    environment:
      __NEXT_PRIVATE_PREBUNDLED_REACT: "next"
      NEXT_PUBLIC_ACL_NO_ACCESS: 1
      NEXT_PUBLIC_ACL_VIEW: 2
      NEXT_PUBLIC_ACL_ADM: 3
      NEXT_PUBLIC_BACKEND_URL: "http://gep.lasicifce.com:5000"
    networks:
      - front-network
 
  ces_frontend:
    build:
      context: ./lasic-ches-front
      dockerfile: Dockerfile
    restart: always
    container_name: ces_frontend
    volumes:
      - ces_static:/home/node/app/.next
    environment:
      NEXT_PUBLIC_FRONTEND_URL: "http://ces_frontend:3000"
      NEXT_PUBLIC_BACKEND_URL: "http://ces.lasicifce.com:5000/v1"
    networks:
      - front-network
 
  cdc_frontend:
    build:
      context: ./centralcompras-front
      dockerfile: Dockerfile
    restart: always
    container_name: cdc_frontend
    volumes:
      - cdc_static:/home/node/app/.next
    environment:
      BACKEND_URL: "http://cdc.lasicifce.com:5000"
    networks:
      - front-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ces_static:/var/www/html/ces:cached
      - cdc_static:/var/www/html/cdc:cached
      - gep_static:/var/www/html/gep:cached
    networks:
      - front-network
    depends_on:
      - gep_frontend
      - ces_frontend
      - cdc_frontend
networks:
  front-network:
    driver: bridge
volumes:
  ces_static:
  cdc_static:
  gep_static:


