services: 
  gep_frontend:
    build:
      context: ./lasic-gep-front-next
      dockerfile: Dockerfile
    restart: always
    container_name: gep_frontend
    environment:
      __NEXT_PRIVATE_PREBUNDLED_REACT: next
      NEXT_PUBLIC_ACL_NO_ACCESS: 1
      NEXT_PUBLIC_ACL_VIEW: 2
      NEXT_PUBLIC_ACL_ADM: 3
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000"
    networks:
      - front-network
 
  ces_frontend:
    build:
      context: ./lasic-ches-front
      dockerfile: Dockerfile
    restart: always
    container_name: ces_frontend
    environment:
      NEXT_PUBLIC_FRONTEND_URL: "http://ces_frontend:3000"
      NEXT_PUBLIC_BACKEND_URL: "http://127.0.0.1:5000/v1"
    networks:
      - front-network
 
  cdc_frontend:
    build:
      context: ./centralcompras-front
      dockerfile: Dockerfile
    restart: always
    container_name: cdc_frontend
    environment:
      BACKEND_URL: "http://localhost:5000"
    networks:
      - front-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front-network
    depends_on:
      - gep_frontend
      - ces_frontend
      - cdc_frontend
networks:
  front-network:
    driver: bridge
