FROM node:20 AS builder

WORKDIR /home/node/app
COPY package.json .
RUN npm install && npm audit fix --force

COPY . .
RUN npm run build
USER node


FROM node:20

WORKDIR /home/node/app

COPY --from=builder /home/node/app .

CMD ["npm", "run", "start", "--", "-p", "8007"]
